import Navbar from '@/components/Navbar';
import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from "@/components/ui/toaster"
import Provider from '@/components/Provider';
import QueryProvider from '@/components/QueryProvider';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  layout = 'center', // Default to 'center' layout
}: {
  children: React.ReactNode;
  layout?: 'center' | 'sidebar'; // Define layout options
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Provider>
          <QueryProvider>
          {/* <main className='h-screen flex'>  */}
          <main className={`h-screen flex ${
              layout === 'center'
                ? 'flex-col justify-center items-center'
                : '' 
            }`}>
            {layout !== 'sidebar' && <Navbar />} {/* Conditionally render Navbar */}
            {children}
          </main>
          <Toaster />
          </QueryProvider>
        </Provider>
      </body>
    </html>
  );
}