name: Run tests

on:
  push:
    branches: 
    - 'main'
    pull_requests:
      branches:
      - 'main'


jobs:
  tests:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout 
      uses: actions/checkout@v2